version: '3'

services:
  postgis:
    # build the container and set the name
    build:
      context: .
      dockerfile: dockerfile.postgis

    container_name: postgis

    # expose the postgres port
    ports:
      - 5432:5432

    # provide password based on environment variable]
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

    volumes:
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data

  #bag:
  #  build:
  #    context: .
  #    dockerfile: dockerfile.bag

   #  container_name: bag

    # link it to postgres
   # links:
   #   - postgres

    # make the /var/www/html volume available as ./app
    #volumes:
    #  - ${BAG_DIR}:/app
